project:
  type: website

website:
  title: "[TBD] Frictions Frequency and Modality vs User Satifaction"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - proposal.qmd

format:
  html:
    theme: cyborg
    toc: true
    code-fold: show
    code-tools: true
  pdf:
    toc: false
    documentclass: article
    colorlinks: true
    geometry:
      - margin=0.8in