project:
  type: website

website:
  title: "[TBD] Frictions Frequency and Modality vs User Satifaction"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - proposal.qmd

format:
  html:
    theme: cyborg
    toc: true
    code-fold: show
    code-tools: true
  pdf:
    toc: false
    documentclass: article
    colorlinks: true
    geometry:
      - margin=0.5in
    linestretch: 1.0
    include-in-header:
      text: |
        \usepackage{enumitem}
        \setlist{nosep,leftmargin=*}
        \usepackage{titling}
        \setlength{\droptitle}{-3em}
        \pretitle{\begin{center}\Large\bfseries}
        \posttitle{\end{center}\vspace{-0.5em}}